server:
  port: 8000

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      routes:
        - id: videoservice
          uri: lb://VIDEOSERVICE
          predicates:
            - Path=/videoservice/**
          filters:
            - StripPrefix=1
        - id: statisticsservice
          uri: lb://STATISTICSSERVICE
          predicates:
            - Path=/statisticsservice/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance.id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaservice:8761/eureka
